// auth-client/src/views/admin/analytics/Reports.vue
<template>
  <div>
    <Breadcrumb :items="breadcrumbItems" />
    
    <div class="bg-white shadow rounded-lg p-6 mt-4">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-xl font-semibold text-gray-800">Analytics Reports</h2>
        <Button type="primary" @click="navigateToNewReport">
          <template #icon><FileAddOutlined /></template>
          Create New Report
        </Button>
      </div>
      
      <!-- Reports Table -->
      <Table
        :columns="columns"
        :data-source="reports"
        :loading="loading"
        :pagination="{ pageSize: 10 }"
        row-key="id"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'type'">
            <Tag :color="getReportTypeColor(record.type)">
              {{ record.type }}
            </Tag>
          </template>
          
          <template v-if="column.key === 'status'">
            <Tag :color="getStatusColor(record.status)">
              {{ record.status }}
            </Tag>
          </template>
          
          <template v-if="column.key === 'actions'">
            <Space>
              <Button 
                type="primary" 
                size="small" 
                @click="viewReport(record)"
                :disabled="record.status === 'PENDING'"
              >
                <template #icon><EyeOutlined /></template>
                View
              </Button>
              <Button 
                type="primary" 
                size="small" 
                @click="downloadReport(record)"
                :disabled="record.status === 'PENDING' || record.status === 'FAILED'"
              >
                <template #icon><DownloadOutlined /></template>
                Download
              </Button>
              <Button 
                type="primary" 
                danger 
                size="small" 
                @click="confirmDeleteReport(record)"
              >
                <template #icon><DeleteOutlined /></template>
                Delete
              </Button>
            </Space>
          </template>
        </template>
      </Table>
    </div>
    
    <!-- Report View Modal -->
    <Modal
      :title="selectedReport?.name"
      :open="reportModalVisible"
      width="800px"
      @cancel="reportModalVisible = false"
      footer={null}
    >
      <Spin :spinning="reportLoading">
        <div v-if="reportData">
          <Tabs>
            <Tabs.TabPane key="preview" tab="Preview">
              <div class="max-h-96 overflow-auto">
                <div v-if="selectedReport?.type === 'USER_ACTIVITY'">
                  <Table
                    :columns="userActivityColumns"
                    :data-source="reportData.data"
                    :pagination="{ pageSize: 5 }"
                    size="small"
                  />
                </div>
                <div v-else-if="selectedReport?.type === 'LOGIN_STATS'">
                  <Table
                    :columns="loginStatsColumns"
                    :data-source="reportData.data"
                    :pagination="{ pageSize: 5 }"
                    size="small"
                  />
                </div>
                <div v-else>
                  <pre class="whitespace-pre-wrap">{{ JSON.stringify(reportData, null, 2) }}</pre>
                </div>
              </div>
            </Tabs.TabPane>
            <Tabs.TabPane key="json" tab="JSON">
              <div class="max-h-96 overflow-auto">
                <pre class="whitespace-pre-wrap">{{ JSON.stringify(reportData, null, 2) }}</pre>
              </div>
            </Tabs.TabPane>
            <Tabs.TabPane key="details" tab="Report Details">
              <Descriptions bordered column={1}>
                <Descriptions.Item label="Name">{{ selectedReport?.name }}</Descriptions.Item>
                <Descriptions.Item label="Type">
                  <Tag :color="getReportTypeColor(selectedReport?.type)">
                    {{ selectedReport?.type }}
                  </Tag>
                </Descriptions.Item>
                <Descriptions.Item label="Status">
                  <Tag :color="getStatusColor(selectedReport?.status)">
                    {{ selectedReport?.status }}
                  </Tag>
                </Descriptions.Item>
                <Descriptions.Item label="Created By">{{ selectedReport?.createdBy?.fullName }}</Descriptions.Item>
                <Descriptions.Item label="Created At">{{ formatDate(selectedReport?.createdAt) }}</Descriptions.Item>
                <Descriptions.Item label="Parameters">
                  <pre class="whitespace-pre-wrap">{{ JSON.stringify(selectedReport?.parameters, null, 2) }}</pre>
                </Descriptions.Item>
              </Descriptions>
            </Tabs.TabPane>
          </Tabs>
        </div>
        <Empty v-else description="No report data available" />
      </Spin>
    </Modal>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import api from '@/services/api'
import { useToast } from '@/components/ui/ToastContainer.vue'
import Breadcrumb from '@/components/ui/Breadcrumb.vue'
import { Button, Table, Tag, Modal, Space, Tabs, Descriptions, Spin, Empty } from 'ant-design-vue'
import { FileAddOutlined, EyeOutlined, DownloadOutlined, DeleteOutlined } from '@ant-design/icons-vue'

// Initialize auth store, router, and toast
const authStore = useAuthStore()
const router = useRouter()
const toast = useToast()

// Breadcrumb items
const breadcrumbItems = [
  { text: 'Dashboard', to: '/admin' },
  { text: 'Analytics', to: '/admin/analytics' },
  { text: 'Reports', to: '/admin/analytics/reports', active: true }
]

// State
const loading = ref(false)
const reportLoading = ref(false)
const reports = ref<any[]>([])
const reportModalVisible = ref(false)
const selectedReport = ref<any>(null)
const reportData = ref<any>(null)

// Table columns
const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
    sorter: (a: any, b: any) => a.name.localeCompare(b.name)
  },
  {
    title: 'Type',
    key: 'type',
    filters: [
      { text: 'User Activity', value: 'USER_ACTIVITY' },
      { text: 'Login Stats', value: 'LOGIN_STATS' },
      { text: 'System Usage', value: 'SYSTEM_USAGE' }
    ],
    onFilter: (value: string, record: any) => record.type === value
  },
  {
    title: 'Status',
    key: 'status',
    filters: [
      { text: 'Completed', value: 'COMPLETED' },
      { text: 'Pending', value: 'PENDING' },
      { text: 'Failed', value: 'FAILED' }
    ],
    onFilter: (value: string, record: any) => record.status === value
  },
  {
    title: 'Created By',
    dataIndex: 'createdBy',
    key: 'createdBy',
    render: (createdBy: any) => createdBy?.fullName || 'System'
  },
  {
    title: 'Created At',
    dataIndex: 'createdAt',
    key: 'createdAt',
    render: (text: string) => formatDate(text),
    sorter: (a: any, b: any) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
  },
  {
    title: 'Actions',
    key: 'actions'
  }
]

// User activity columns for report preview
const userActivityColumns = [
  {
    title: 'User',
    dataIndex: 'username',
    key: 'username'
  },
  {
    title: 'Action',
    dataIndex: 'action',
    key: 'action'
  },
  {
    title: 'Timestamp',
    dataIndex: 'timestamp',
    key: 'timestamp',
    render: (text: string) => formatDate(text)
  },
  {
    title: 'IP Address',
    dataIndex: 'ipAddress',
    key: 'ipAddress'
  }
]

// Login stats columns for report preview
const loginStatsColumns = [
  {
    title: 'Date',
    dataIndex: 'date',
    key: 'date'
  },
  {
    title: 'Successful Logins',
    dataIndex: 'successfulLogins',
    key: 'successfulLogins'
  },
  {
    title: 'Failed Logins',
    dataIndex: 'failedLogins',
    key: 'failedLogins'
  },
  {
    title: 'Unique Users',
    dataIndex: 'uniqueUsers',
    key: 'uniqueUsers'
  }
]

// Format date
const formatDate = (date: string) => {
  if (!date) return ''
  return new Date(date).toLocaleString()
}

// Get report type color
const getReportTypeColor = (type: string) => {
  switch (type) {
    case 'USER_ACTIVITY':
      return 'blue'
    case 'LOGIN_STATS':
      return 'green'
    case 'SYSTEM_USAGE':
      return 'purple'
    default:
      return 'default'
  }
}

// Get status color
const getStatusColor = (status: string) => {
  switch (status) {
    case 'COMPLETED':
      return 'success'
    case 'PENDING':
      return 'processing'
    case 'FAILED':
      return 'error'
    default:
      return 'default'
  }
}

// Navigate to new report page
const navigateToNewReport = () => {
  router.push('/admin/analytics/reports/new')
}

// Fetch reports
const fetchReports = async () => {
  try {
    loading.value = true
    
    const response = await api.get('/admin/reports', {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    // Process response
    if (response.data && response.data.data) {
      reports.value = response.data.data
    } else {
      reports.value = response.data || []
    }
  } catch (error) {
    console.error('Error fetching reports:', error)
    toast.error('Failed to load reports')
  } finally {
    loading.value = false
  }
}

// View report
const viewReport = async (report: any) => {
  try {
    selectedReport.value = report
    reportModalVisible.value = true
    reportLoading.value = true
    reportData.value = null
    
    const response = await api.get(`/admin/reports/${report.id}/data`, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    // Process response
    if (response.data && response.data.data) {
      reportData.value = response.data.data
    } else {
      reportData.value = response.data || null
    }
  } catch (error) {
    console.error('Error fetching report data:', error)
    toast.error('Failed to load report data')
  } finally {
    reportLoading.value = false
  }
}

// Download report
const downloadReport = async (report: any) => {
  try {
    const response = await api.get(`/admin/reports/${report.id}/download`, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      },
      responseType: 'blob'
    })
    
    // Create download link
    const url = window.URL.createObjectURL(new Blob([response.data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `${report.name}.json`)
    document.body.appendChild(link)
    link.click()
    link.remove()
    
    toast.success('Report downloaded successfully')
  } catch (error) {
    console.error('Error downloading report:', error)
    toast.error('Failed to download report')
  }
}

// Delete report
const confirmDeleteReport = (report: any) => {
  Modal.confirm({
    title: 'Are you sure you want to delete this report?',
    content: 'This action cannot be undone.',
    okText: 'Yes, Delete',
    okType: 'danger',
    cancelText: 'Cancel',
    onOk: () => deleteReport(report.id)
  })
}

const deleteReport = async (reportId: string) => {
  try {
    loading.value = true
    
    await api.delete(`/admin/reports/${reportId}`, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    // Remove from list
    reports.value = reports.value.filter(report => report.id !== reportId)
    
    toast.success('Report deleted successfully')
  } catch (error) {
    console.error('Error deleting report:', error)
    toast.error('Failed to delete report')
  } finally {
    loading.value = false
  }
}

// Initialize on mount
onMounted(() => {
  fetchReports()
})
</script>

// auth-client-react/src/pages/admin/analytics/Reports.tsx
import React, { useState, useEffect } from 'react';
import { 
  Card, 
  Table, 
  Button, 
  Typography, 
  Space, 
  Popconfirm, 
  message,
  Tag,
  Tooltip,
} from 'antd';
import { 
  PlusOutlined, 
  DeleteOutlined, 
  ExclamationCircleOutlined,
  PlayCircleOutlined,
  DownloadOutlined,
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { useNavigate } from 'react-router-dom';
import adminService from '../../../services/admin.service';

const { Title, Text } = Typography;

interface ReportData {
  id: string;
  name: string;
  description: string;
  type: string;
  createdAt: string;
  createdBy: string;
  lastRun: string | null;
  schedule: string | null;
}

const Reports: React.FC = () => {
  const [reports, setReports] = useState<ReportData[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [runningReports, setRunningReports] = useState<Set<string>>(new Set());
  const [pagination, setPagination] = useState({
    current: 1,
    pageSize: 10,
    total: 0,
  });
  const navigate = useNavigate();

  // Fetch reports on component mount and pagination change
  useEffect(() => {
    fetchReports();
  }, [pagination.current, pagination.pageSize]);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const data = await adminService.getReports(pagination.current, pagination.pageSize);
      setReports(data.reports);
      setPagination({
        ...pagination,
        total: data.total,
      });
    } catch (error) {
      console.error('Failed to fetch reports:', error);
      message.error('Failed to load reports');
    } finally {
      setLoading(false);
    }
  };

  const handleRunReport = async (id: string) => {
    try {
      setRunningReports(prev => new Set(prev).add(id));
      await adminService.runReport(id);
      message.success('Report generation started');
      
      // In a real application, you would poll for report status
      // For now, we'll simulate completion after 3 seconds
      setTimeout(() => {
        setRunningReports(prev => {
          const newSet = new Set(prev);
          newSet.delete(id);
          return newSet;
        });
        message.success('Report generated successfully');
        fetchReports();
      }, 3000);
    } catch (error) {
      console.error('Failed to run report:', error);
      message.error('Failed to run report');
      setRunningReports(prev => {
        const newSet = new Set(prev);
        newSet.delete(id);
        return newSet;
      });
    }
  };

  const handleDeleteReport = async (id: string) => {
    try {
      await adminService.deleteReport(id);
      message.success('Report deleted successfully');
      fetchReports();
    } catch (error) {
      console.error('Failed to delete report:', error);
      message.error('Failed to delete report');
    }
  };

  const handleTableChange = (pagination: any) => {
    setPagination({
      ...pagination,
      current: pagination.current,
      pageSize: pagination.pageSize,
    });
  };

  const getReportTypeTag = (type: string) => {
    switch (type) {
      case 'user_activity':
        return <Tag color="blue">User Activity</Tag>;
      case 'login_attempts':
        return <Tag color="green">Login Attempts</Tag>;
      case 'security_audit':
        return <Tag color="red">Security Audit</Tag>;
      case 'system_usage':
        return <Tag color="orange">System Usage</Tag>;
      default:
        return <Tag>{type}</Tag>;
    }
  };

  const getScheduleTag = (schedule: string | null) => {
    if (!schedule) return <Tag>On Demand</Tag>;
    
    switch (schedule) {
      case 'daily':
        return <Tag color="blue">Daily</Tag>;
      case 'weekly':
        return <Tag color="green">Weekly</Tag>;
      case 'monthly':
        return <Tag color="purple">Monthly</Tag>;
      default:
        return <Tag>{schedule}</Tag>;
    }
  };

  const columns: ColumnsType<ReportData> = [
    {
      title: 'Report Name',
      dataIndex: 'name',
      key: 'name',
      render: (text: string) => (
        <span style={{ fontWeight: 'bold' }}>{text}</span>
      ),
    },
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => getReportTypeTag(type),
    },
    {
      title: 'Schedule',
      dataIndex: 'schedule',
      key: 'schedule',
      render: (schedule: string | null) => getScheduleTag(schedule),
    },
    {
      title: 'Last Run',
      dataIndex: 'lastRun',
      key: 'lastRun',
      render: (lastRun: string | null) => 
        lastRun ? new Date(lastRun).toLocaleString() : 'Never',
    },
    {
      title: 'Created By',
      dataIndex: 'createdBy',
      key: 'createdBy',
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 200,
      render: (_, record) => (
        <Space size="small">
          <Tooltip title="Run Report">
            <Button
              type="primary"
              icon={<PlayCircleOutlined />}
              size="small"
              loading={runningReports.has(record.id)}
              onClick={() => handleRunReport(record.id)}
            />
          </Tooltip>
          <Tooltip title="Download Report">
            <Button
              icon={<DownloadOutlined />}
              size="small"
              disabled={!record.lastRun}
            />
          </Tooltip>
          <Tooltip title="Delete Report">
            <Popconfirm
              title="Are you sure you want to delete this report?"
              onConfirm={() => handleDeleteReport(record.id)}
              okText="Yes"
              cancelText="No"
              icon={<ExclamationCircleOutlined style={{ color: 'red' }} />}
            >
              <Button
                type="primary"
                danger
                icon={<DeleteOutlined />}
                size="small"
              />
            </Popconfirm>
          </Tooltip>
        </Space>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <Title level={2}>Reports</Title>
        <Button
          type="primary"
          icon={<PlusOutlined />}
          onClick={() => navigate('/admin/analytics/reports/new')}
        >
          Create New Report
        </Button>
      </div>

      <Card>
        <Text className="block mb-4">
          View and manage analytics reports. Run reports on demand or schedule them to run automatically.
        </Text>
        <Table
          columns={columns}
          dataSource={reports}
          rowKey="id"
          loading={loading}
          pagination={pagination}
          onChange={handleTableChange}
        />
      </Card>
    </div>
  );
};

export default Reports;
