// auth-client-react/src/pages/admin/analytics/NewReport.tsx
import React, { useState } from 'react';
import {
  Card,
  Form,
  Input,
  Button,
  Select,
  Typography,
  Divider,
  message,
  Alert,
  Radio,
  DatePicker,
  Space
} from 'antd';
import {
  SaveOutlined,
  FileTextOutlined,
} from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import adminService from '../../../services/admin.service';

const { Title, Text } = Typography;
const { Option } = Select;
const { TextArea } = Input;
const { RangePicker } = DatePicker;

const NewReport: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [reportType, setReportType] = useState<string>('user_activity');
  const [scheduleType, setScheduleType] = useState<string>('on_demand');
  const navigate = useNavigate();

  const onFinish = async (values: any) => {
    try {
      setLoading(true);
      setError(null);

      // Process date range if provided
      if (values.dateRange) {
        values.startDate = values.dateRange[0].toISOString();
        values.endDate = values.dateRange[1].toISOString();
        delete values.dateRange;
      }

      // Process schedule
      if (values.scheduleType === 'on_demand') {
        values.schedule = null;
      } else {
        values.schedule = values.scheduleType;
      }
      delete values.scheduleType;

      await adminService.createReport(values);
      message.success('Report created successfully');

      // Navigate to reports list
      navigate('/admin/analytics/reports');
    } catch (err: any) {
      console.error('Failed to create report:', err);
      setError(err.message || 'Failed to create report');
    } finally {
      setLoading(false);
    }
  };

  const handleReportTypeChange = (value: string) => {
    setReportType(value);
  };

  const handleScheduleTypeChange = (e: any) => {
    setScheduleType(e.target.value);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <Title level={2}>Create New Report</Title>
        <Button
          type="primary"
          onClick={() => navigate('/admin/analytics/reports')}
        >
          Back to Reports
        </Button>
      </div>

      <Card>
        {error && (
          <Alert
            message="Error"
            description={error}
            type="error"
            showIcon
            closable
            className="mb-6"
            onClose={() => setError(null)}
          />
        )}

        <Form
          form={form}
          layout="vertical"
          onFinish={onFinish}
          initialValues={{
            type: 'user_activity',
            scheduleType: 'on_demand',
          }}
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <Title level={4}>Report Information</Title>
              <Text type="secondary" className="block mb-4">
                Enter the basic information for the new report.
              </Text>

              <Form.Item
                name="name"
                label="Report Name"
                rules={[{ required: true, message: 'Please enter report name' }]}
              >
                <Input prefix={<FileTextOutlined />} placeholder="Report Name" />
              </Form.Item>

              <Form.Item
                name="description"
                label="Description"
                rules={[{ required: true, message: 'Please enter description' }]}
              >
                <TextArea
                  rows={4}
                  placeholder="Describe the purpose of this report"
                />
              </Form.Item>

              <Form.Item
                name="type"
                label="Report Type"
                rules={[{ required: true, message: 'Please select report type' }]}
              >
                <Select onChange={handleReportTypeChange}>
                  <Option value="user_activity">User Activity</Option>
                  <Option value="login_attempts">Login Attempts</Option>
                  <Option value="security_audit">Security Audit</Option>
                  <Option value="system_usage">System Usage</Option>
                </Select>
              </Form.Item>
            </div>

            <div>
              <Title level={4}>Report Settings</Title>
              <Text type="secondary" className="block mb-4">
                Configure when and how the report should run.
              </Text>

              <Form.Item
                name="dateRange"
                label="Date Range"
                rules={[{ required: true, message: 'Please select date range' }]}
              >
                <RangePicker style={{ width: '100%' }} />
              </Form.Item>

              <Form.Item
                name="scheduleType"
                label="Schedule"
              >
                <Radio.Group onChange={handleScheduleTypeChange}>
                  <Space direction="vertical">
                    <Radio value="on_demand">Run on demand</Radio>
                    <Radio value="daily">Daily</Radio>
                    <Radio value="weekly">Weekly</Radio>
                    <Radio value="monthly">Monthly</Radio>
                  </Space>
                </Radio.Group>
              </Form.Item>

              {scheduleType !== 'on_demand' && (
                <Form.Item
                  name="scheduleTime"
                  label="Time to Run"
                  rules={[{ required: true, message: 'Please select time to run' }]}
                >
                  <Select>
                    <Option value="00:00">12:00 AM</Option>
                    <Option value="06:00">6:00 AM</Option>
                    <Option value="12:00">12:00 PM</Option>
                    <Option value="18:00">6:00 PM</Option>
                  </Select>
                </Form.Item>
              )}

              <Form.Item
                name="format"
                label="Output Format"
                rules={[{ required: true, message: 'Please select output format' }]}
                initialValue="pdf"
              >
                <Select>
                  <Option value="pdf">PDF</Option>
                  <Option value="csv">CSV</Option>
                  <Option value="excel">Excel</Option>
                  <Option value="json">JSON</Option>
                </Select>
              </Form.Item>
            </div>
          </div>

          <Divider />

          <div className="flex justify-end">
            <Button
              type="default"
              onClick={() => navigate('/admin/analytics/reports')}
              className="mr-2"
            >
              Cancel
            </Button>
            <Button
              type="primary"
              htmlType="submit"
              icon={<SaveOutlined />}
              loading={loading}
            >
              Create Report
            </Button>
          </div>
        </Form>
      </Card>
    </div>
  );
};

export default NewReport;

// auth-client/src/views/admin/analytics/NewReport.vue
<template>
  <div>
    <Breadcrumb :items="breadcrumbItems" />

    <div class="bg-white shadow rounded-lg p-6 mt-4">
      <h2 class="text-xl font-semibold text-gray-800 mb-4">Create New Report</h2>

      <Form
        :model="reportForm"
        layout="vertical"
        @finish="handleSubmit"
      >
        <Row :gutter="16">
          <Col :span="12">
            <Form.Item
              label="Report Name"
              name="name"
              :rules="[{ required: true, message: 'Please enter report name' }]"
            >
              <Input v-model:value="reportForm.name" placeholder="Enter report name" />
            </Form.Item>
          </Col>

          <Col :span="12">
            <Form.Item
              label="Report Type"
              name="type"
              :rules="[{ required: true, message: 'Please select report type' }]"
            >
              <Select
                v-model:value="reportForm.type"
                placeholder="Select report type"
                @change="handleReportTypeChange"
              >
                <Select.Option value="USER_ACTIVITY">User Activity</Select.Option>
                <Select.Option value="LOGIN_STATS">Login Statistics</Select.Option>
                <Select.Option value="SYSTEM_USAGE">System Usage</Select.Option>
              </Select>
            </Form.Item>
          </Col>
        </Row>

        <Row :gutter="16">
          <Col :span="24">
            <Form.Item
              label="Description"
              name="description"
            >
              <Input.TextArea v-model:value="reportForm.description" rows="3" placeholder="Enter report description" />
            </Form.Item>
          </Col>
        </Row>

        <!-- Dynamic parameters based on report type -->
        <div v-if="reportForm.type === 'USER_ACTIVITY'">
          <Divider>User Activity Parameters</Divider>

          <Row :gutter="16">
            <Col :span="12">
              <Form.Item
                label="Date Range"
                name="dateRange"
                :rules="[{ required: true, message: 'Please select date range' }]"
              >
                <DatePicker.RangePicker
                  v-model:value="reportForm.parameters.dateRange"
                  style="width: 100%"
                  :disabled-date="disabledDate"
                />
              </Form.Item>
            </Col>

            <Col :span="12">
              <Form.Item
                label="User"
                name="userId"
              >
                <Select
                  v-model:value="reportForm.parameters.userId"
                  placeholder="Select user (optional)"
                  allowClear
                  style="width: 100%"
                >
                  <Select.Option value="">All Users</Select.Option>
                  <Select.Option v-for="user in users" :key="user.id" :value="user.id">
                    {{ user.fullName }} ({{ user.username }})
                  </Select.Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>

          <Row :gutter="16">
            <Col :span="12">
              <Form.Item
                label="Activity Types"
                name="activityTypes"
              >
                <Select
                  v-model:value="reportForm.parameters.activityTypes"
                  mode="multiple"
                  placeholder="Select activity types (optional)"
                  style="width: 100%"
                  allowClear
                >
                  <Select.Option value="LOGIN">Login</Select.Option>
                  <Select.Option value="LOGOUT">Logout</Select.Option>
                  <Select.Option value="REGISTER">Register</Select.Option>
                  <Select.Option value="PASSWORD_RESET">Password Reset</Select.Option>
                  <Select.Option value="PROFILE_UPDATE">Profile Update</Select.Option>
                </Select>
              </Form.Item>
            </Col>

            <Col :span="12">
              <Form.Item
                label="Include Details"
                name="includeDetails"
                valuePropName="checked"
              >
                <Checkbox v-model:checked="reportForm.parameters.includeDetails">
                  Include detailed activity information
                </Checkbox>
              </Form.Item>
            </Col>
          </Row>
        </div>

        <div v-else-if="reportForm.type === 'LOGIN_STATS'">
          <Divider>Login Statistics Parameters</Divider>

          <Row :gutter="16">
            <Col :span="12">
              <Form.Item
                label="Date Range"
                name="dateRange"
                :rules="[{ required: true, message: 'Please select date range' }]"
              >
                <DatePicker.RangePicker
                  v-model:value="reportForm.parameters.dateRange"
                  style="width: 100%"
                  :disabled-date="disabledDate"
                />
              </Form.Item>
            </Col>

            <Col :span="12">
              <Form.Item
                label="Group By"
                name="groupBy"
              >
                <Select
                  v-model:value="reportForm.parameters.groupBy"
                  placeholder="Select grouping"
                  style="width: 100%"
                >
                  <Select.Option value="day">Day</Select.Option>
                  <Select.Option value="week">Week</Select.Option>
                  <Select.Option value="month">Month</Select.Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>

          <Row :gutter="16">
            <Col :span="12">
              <Form.Item
                label="Include Failed Logins"
                name="includeFailedLogins"
                valuePropName="checked"
              >
                <Checkbox v-model:checked="reportForm.parameters.includeFailedLogins">
                  Include failed login attempts
                </Checkbox>
              </Form.Item>
            </Col>

            <Col :span="12">
              <Form.Item
                label="Include Device Info"
                name="includeDeviceInfo"
                valuePropName="checked"
              >
                <Checkbox v-model:checked="reportForm.parameters.includeDeviceInfo">
                  Include device and browser information
                </Checkbox>
              </Form.Item>
            </Col>
          </Row>
        </div>

        <div v-else-if="reportForm.type === 'SYSTEM_USAGE'">
          <Divider>System Usage Parameters</Divider>

          <Row :gutter="16">
            <Col :span="12">
              <Form.Item
                label="Date Range"
                name="dateRange"
                :rules="[{ required: true, message: 'Please select date range' }]"
              >
                <DatePicker.RangePicker
                  v-model:value="reportForm.parameters.dateRange"
                  style="width: 100%"
                  :disabled-date="disabledDate"
                />
              </Form.Item>
            </Col>

            <Col :span="12">
              <Form.Item
                label="Metrics"
                name="metrics"
                :rules="[{ required: true, message: 'Please select at least one metric' }]"
              >
                <Select
                  v-model:value="reportForm.parameters.metrics"
                  mode="multiple"
                  placeholder="Select metrics"
                  style="width: 100%"
                >
                  <Select.Option value="activeUsers">Active Users</Select.Option>
                  <Select.Option value="newUsers">New Users</Select.Option>
                  <Select.Option value="apiCalls">API Calls</Select.Option>
                  <Select.Option value="errors">Errors</Select.Option>
                  <Select.Option value="avgResponseTime">Average Response Time</Select.Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>

          <Row :gutter="16">
            <Col :span="12">
              <Form.Item
                label="Group By"
                name="groupBy"
              >
                <Select
                  v-model:value="reportForm.parameters.groupBy"
                  placeholder="Select grouping"
                  style="width: 100%"
                >
                  <Select.Option value="hour">Hour</Select.Option>
                  <Select.Option value="day">Day</Select.Option>
                  <Select.Option value="week">Week</Select.Option>
                  <Select.Option value="month">Month</Select.Option>
                </Select>
              </Form.Item>
            </Col>

            <Col :span="12">
              <Form.Item
                label="Format"
                name="format"
              >
                <Select
                  v-model:value="reportForm.parameters.format"
                  placeholder="Select output format"
                  style="width: 100%"
                >
                  <Select.Option value="json">JSON</Select.Option>
                  <Select.Option value="csv">CSV</Select.Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>
        </div>

        <Form.Item style="margin-top: 24px">
          <Button type="primary" html-type="submit" :loading="submitting">
            <template #icon><FileAddOutlined /></template>
            Generate Report
          </Button>
          <Button style="margin-left: 8px" @click="resetForm">
            Reset
          </Button>
        </Form.Item>
      </Form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import api from '@/services/api'
import { useToast } from '@/components/ui/ToastContainer.vue'
import Breadcrumb from '@/components/ui/Breadcrumb.vue'
import { Button, Form, Input, Select, DatePicker, Checkbox, Divider, Row, Col } from 'ant-design-vue'
import { FileAddOutlined } from '@ant-design/icons-vue'
import dayjs from 'dayjs'

// Initialize auth store, router, and toast
const authStore = useAuthStore()
const router = useRouter()
const toast = useToast()

// Breadcrumb items
const breadcrumbItems = [
  { text: 'Dashboard', to: '/admin' },
  { text: 'Analytics', to: '/admin/analytics' },
  { text: 'Reports', to: '/admin/analytics/reports' },
  { text: 'New Report', to: '/admin/analytics/reports/new', active: true }
]

// State
const submitting = ref(false)
const users = ref<any[]>([])

// Report form
const reportForm = ref({
  name: '',
  type: '',
  description: '',
  parameters: {
    // User Activity parameters
    dateRange: [dayjs().subtract(30, 'days'), dayjs()],
    userId: '',
    activityTypes: [],
    includeDetails: true,

    // Login Stats parameters
    groupBy: 'day',
    includeFailedLogins: true,
    includeDeviceInfo: true,

    // System Usage parameters
    metrics: ['activeUsers', 'newUsers'],
    format: 'json'
  }
})

// Disabled date (future dates)
const disabledDate = (current: dayjs.Dayjs) => {
  return current && current > dayjs().endOf('day')
}

// Handle report type change
const handleReportTypeChange = (value: string) => {
  // Reset parameters
  reportForm.value.parameters = {
    ...reportForm.value.parameters,
    dateRange: [dayjs().subtract(30, 'days'), dayjs()]
  }

  // Set default parameters based on report type
  if (value === 'USER_ACTIVITY') {
    reportForm.value.parameters = {
      ...reportForm.value.parameters,
      userId: '',
      activityTypes: [],
      includeDetails: true
    }
  } else if (value === 'LOGIN_STATS') {
    reportForm.value.parameters = {
      ...reportForm.value.parameters,
      groupBy: 'day',
      includeFailedLogins: true,
      includeDeviceInfo: true
    }
  } else if (value === 'SYSTEM_USAGE') {
    reportForm.value.parameters = {
      ...reportForm.value.parameters,
      metrics: ['activeUsers', 'newUsers'],
      groupBy: 'day',
      format: 'json'
    }
  }
}

// Fetch users
const fetchUsers = async () => {
  try {
    const response = await api.post('/admin/users', {}, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })

    // Process response
    if (response.data && response.data.data) {
      users.value = response.data.data
    } else {
      users.value = response.data || []
    }
  } catch (error) {
    console.error('Error fetching users:', error)
    toast.error('Failed to load users')
  }
}

// Submit form
const handleSubmit = async () => {
  try {
    submitting.value = true

    // Prepare parameters
    const parameters: any = {}

    // Common parameters
    if (reportForm.value.parameters.dateRange && reportForm.value.parameters.dateRange.length === 2) {
      parameters.startDate = reportForm.value.parameters.dateRange[0].toISOString()
      parameters.endDate = reportForm.value.parameters.dateRange[1].toISOString()
    }

    // Type-specific parameters
    if (reportForm.value.type === 'USER_ACTIVITY') {
      if (reportForm.value.parameters.userId) {
        parameters.userId = reportForm.value.parameters.userId
      }

      if (reportForm.value.parameters.activityTypes && reportForm.value.parameters.activityTypes.length > 0) {
        parameters.activityTypes = reportForm.value.parameters.activityTypes
      }

      parameters.includeDetails = reportForm.value.parameters.includeDetails
    } else if (reportForm.value.type === 'LOGIN_STATS') {
      parameters.groupBy = reportForm.value.parameters.groupBy
      parameters.includeFailedLogins = reportForm.value.parameters.includeFailedLogins
      parameters.includeDeviceInfo = reportForm.value.parameters.includeDeviceInfo
    } else if (reportForm.value.type === 'SYSTEM_USAGE') {
      parameters.metrics = reportForm.value.parameters.metrics
      parameters.groupBy = reportForm.value.parameters.groupBy
      parameters.format = reportForm.value.parameters.format
    }

    // Create report request
    const reportRequest = {
      name: reportForm.value.name,
      type: reportForm.value.type,
      description: reportForm.value.description || null,
      parameters
    }

    const response = await api.post('/admin/reports', reportRequest, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })

    toast.success('Report created successfully')

    // Navigate to reports list
    router.push('/admin/analytics/reports')
  } catch (error: any) {
    console.error('Error creating report:', error)

    if (error.response?.data?.message) {
      toast.error(error.response.data.message)
    } else {
      toast.error('Failed to create report')
    }
  } finally {
    submitting.value = false
  }
}

// Reset form
const resetForm = () => {
  reportForm.value = {
    name: '',
    type: '',
    description: '',
    parameters: {
      dateRange: [dayjs().subtract(30, 'days'), dayjs()],
      userId: '',
      activityTypes: [],
      includeDetails: true,
      groupBy: 'day',
      includeFailedLogins: true,
      includeDeviceInfo: true,
      metrics: ['activeUsers', 'newUsers'],
      format: 'json'
    }
  }
}

// Initialize on mount
onMounted(() => {
  fetchUsers()
})
</script>
