// auth-client-react/src/pages/admin/users/NewUser.tsx
import React, { useState, useEffect } from 'react';
import { 
  Card, 
  Form, 
  Input, 
  Button, 
  Select, 
  Switch, 
  Typography, 
  Divider, 
  message,
  Alert
} from 'antd';
import { 
  UserOutlined, 
  MailOutlined, 
  LockOutlined, 
  SaveOutlined,
  UserAddOutlined
} from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import adminService from '../../../services/admin.service';

const { Title, Text } = Typography;
const { Option } = Select;

interface RoleData {
  id: string;
  name: string;
  description: string;
}

const NewUser: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState<boolean>(false);
  const [roles, setRoles] = useState<RoleData[]>([]);
  const [rolesLoading, setRolesLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  // Fetch roles on component mount
  useEffect(() => {
    fetchRoles();
  }, []);

  const fetchRoles = async () => {
    try {
      setRolesLoading(true);
      const data = await adminService.getRoles();
      setRoles(data);
    } catch (error) {
      console.error('Failed to fetch roles:', error);
      message.error('Failed to load roles');
    } finally {
      setRolesLoading(false);
    }
  };

  const onFinish = async (values: any) => {
    try {
      setLoading(true);
      setError(null);
      
      await adminService.createUser(values);
      message.success('User created successfully');
      
      // Navigate to user list
      navigate('/admin/users/list');
    } catch (err: any) {
      console.error('Failed to create user:', err);
      setError(err.message || 'Failed to create user');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <Title level={2}>Create New User</Title>
        <Button 
          type="primary" 
          onClick={() => navigate('/admin/users/list')}
        >
          Back to Users
        </Button>
      </div>

      <Card>
        {error && (
          <Alert
            message="Error"
            description={error}
            type="error"
            showIcon
            closable
            className="mb-6"
            onClose={() => setError(null)}
          />
        )}

        <Form
          form={form}
          layout="vertical"
          onFinish={onFinish}
          initialValues={{
            active: true,
            role: 'USER',
          }}
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <Title level={4}>User Information</Title>
              <Text type="secondary" className="block mb-4">
                Enter the basic information for the new user.
              </Text>

              <Form.Item
                name="fullName"
                label="Full Name"
                rules={[{ required: true, message: 'Please enter full name' }]}
              >
                <Input prefix={<UserOutlined />} placeholder="Full Name" />
              </Form.Item>

              <Form.Item
                name="username"
                label="Username"
                rules={[
                  { required: true, message: 'Please enter username' },
                  { min: 4, message: 'Username must be at least 4 characters' },
                  { pattern: /^[a-zA-Z0-9_]+$/, message: 'Username can only contain letters, numbers and underscores' },
                ]}
              >
                <Input prefix={<UserOutlined />} placeholder="Username" />
              </Form.Item>

              <Form.Item
                name="email"
                label="Email"
                rules={[
                  { required: true, message: 'Please enter email' },
                  { type: 'email', message: 'Please enter a valid email' },
                ]}
              >
                <Input prefix={<MailOutlined />} placeholder="Email" />
              </Form.Item>
            </div>

            <div>
              <Title level={4}>Account Settings</Title>
              <Text type="secondary" className="block mb-4">
                Configure the user's account settings and permissions.
              </Text>

              <Form.Item
                name="password"
                label="Password"
                rules={[
                  { required: true, message: 'Please enter password' },
                  { min: 8, message: 'Password must be at least 8 characters' },
                ]}
              >
                <Input.Password prefix={<LockOutlined />} placeholder="Password" />
              </Form.Item>

              <Form.Item
                name="role"
                label="Role"
                rules={[{ required: true, message: 'Please select a role' }]}
              >
                <Select loading={rolesLoading}>
                  {roles.map(role => (
                    <Option key={role.id} value={role.name}>
                      {role.name} - {role.description}
                    </Option>
                  ))}
                </Select>
              </Form.Item>

              <Form.Item
                name="active"
                label="Account Status"
                valuePropName="checked"
              >
                <Switch 
                  checkedChildren="Active" 
                  unCheckedChildren="Inactive" 
                />
              </Form.Item>
            </div>
          </div>

          <Divider />

          <div className="flex justify-end">
            <Button 
              type="default" 
              onClick={() => navigate('/admin/users/list')}
              className="mr-2"
            >
              Cancel
            </Button>
            <Button 
              type="primary" 
              htmlType="submit" 
              icon={<SaveOutlined />}
              loading={loading}
            >
              Create User
            </Button>
          </div>
        </Form>
      </Card>
    </div>
  );
};

export default NewUser;

// auth-client/src/views/admin/users/NewUser.vue
<template>
  <div>
    <Breadcrumb :items="breadcrumbItems" />
    
    <div class="bg-white shadow rounded-lg p-6 mt-4">
      <h2 class="text-xl font-semibold text-gray-800 mb-4">Create New User</h2>
      
      <Form
        :model="userForm"
        layout="vertical"
        @finish="handleSubmit"
      >
        <Row :gutter="16">
          <Col :span="12">
            <Form.Item
              label="Username"
              name="username"
              :rules="[
                { required: true, message: 'Please enter username' },
                { min: 3, message: 'Username must be at least 3 characters' }
              ]"
            >
              <Input v-model:value="userForm.username" placeholder="Enter username" />
            </Form.Item>
          </Col>
          
          <Col :span="12">
            <Form.Item
              label="Email"
              name="email"
              :rules="[
                { required: true, message: 'Please enter email' },
                { type: 'email', message: 'Please enter a valid email' }
              ]"
            >
              <Input v-model:value="userForm.email" placeholder="Enter email address" />
            </Form.Item>
          </Col>
        </Row>
        
        <Row :gutter="16">
          <Col :span="12">
            <Form.Item
              label="Full Name"
              name="fullName"
              :rules="[{ required: true, message: 'Please enter full name' }]"
            >
              <Input v-model:value="userForm.fullName" placeholder="Enter full name" />
            </Form.Item>
          </Col>
          
          <Col :span="12">
            <Form.Item
              label="Role"
              name="role"
              :rules="[{ required: true, message: 'Please select a role' }]"
            >
              <Select v-model:value="userForm.role" placeholder="Select role">
                <Select.Option value="USER">User</Select.Option>
                <Select.Option value="ADMIN">Admin</Select.Option>
              </Select>
            </Form.Item>
          </Col>
        </Row>
        
        <Row :gutter="16">
          <Col :span="12">
            <Form.Item
              label="Password"
              name="password"
              :rules="[
                { required: true, message: 'Please enter password' },
                { min: 8, message: 'Password must be at least 8 characters' }
              ]"
            >
              <Input.Password v-model:value="userForm.password" placeholder="Enter password" />
            </Form.Item>
          </Col>
          
          <Col :span="12">
            <Form.Item
              label="Confirm Password"
              name="confirmPassword"
              :rules="[
                { required: true, message: 'Please confirm password' },
                { validator: validateConfirmPassword }
              ]"
            >
              <Input.Password v-model:value="userForm.confirmPassword" placeholder="Confirm password" />
            </Form.Item>
          </Col>
        </Row>
        
        <Form.Item
          label="Avatar URL (Optional)"
          name="avatar"
        >
          <Input v-model:value="userForm.avatar" placeholder="Enter avatar URL" />
        </Form.Item>
        
        <Form.Item
          name="active"
          valuePropName="checked"
        >
          <Checkbox v-model:checked="userForm.active">Account is active</Checkbox>
        </Form.Item>
        
        <Form.Item
          name="emailVerified"
          valuePropName="checked"
        >
          <Checkbox v-model:checked="userForm.emailVerified">Email is verified</Checkbox>
        </Form.Item>
        
        <Form.Item>
          <Button type="primary" html-type="submit" :loading="submitting">
            <template #icon><UserAddOutlined /></template>
            Create User
          </Button>
          <Button style="margin-left: 8px" @click="resetForm">
            Reset
          </Button>
        </Form.Item>
      </Form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import api from '@/services/api'
import { useToast } from '@/components/ui/ToastContainer.vue'
import Breadcrumb from '@/components/ui/Breadcrumb.vue'
import { Button, Form, Input, Select, Checkbox, Row, Col } from 'ant-design-vue'
import { UserAddOutlined } from '@ant-design/icons-vue'

// Initialize auth store, router, and toast
const authStore = useAuthStore()
const router = useRouter()
const toast = useToast()

// Breadcrumb items
const breadcrumbItems = [
  { text: 'Dashboard', to: '/admin' },
  { text: 'Users', to: '/admin/users' },
  { text: 'New User', to: '/admin/users/new', active: true }
]

// State
const submitting = ref(false)

// User form
const userForm = ref({
  username: '',
  email: '',
  fullName: '',
  password: '',
  confirmPassword: '',
  role: 'USER',
  avatar: '',
  active: true,
  emailVerified: true
})

// Validate confirm password
const validateConfirmPassword = (_rule: any, value: string) => {
  if (value !== userForm.value.password) {
    return Promise.reject('The two passwords do not match')
  }
  return Promise.resolve()
}

// Submit form
const handleSubmit = async () => {
  try {
    submitting.value = true
    
    // Create user object (omit confirmPassword)
    const userData = {
      username: userForm.value.username,
      email: userForm.value.email,
      fullName: userForm.value.fullName,
      password: userForm.value.password,
      role: userForm.value.role,
      avatar: userForm.value.avatar || null,
      active: userForm.value.active,
      emailVerified: userForm.value.emailVerified
    }
    
    const response = await api.post('/admin/users', userData, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    toast.success('User created successfully')
    
    // Navigate to user list
    router.push('/admin/users/list')
  } catch (error: any) {
    console.error('Error creating user:', error)
    
    if (error.response?.data?.message) {
      toast.error(error.response.data.message)
    } else {
      toast.error('Failed to create user')
    }
  } finally {
    submitting.value = false
  }
}

// Reset form
const resetForm = () => {
  userForm.value = {
    username: '',
    email: '',
    fullName: '',
    password: '',
    confirmPassword: '',
    role: 'USER',
    avatar: '',
    active: true,
    emailVerified: true
  }
}
</script>
