// auth-client/src/views/admin/users/UserInvites.vue
<template>
  <div>
    <Breadcrumb :items="breadcrumbItems" />
    
    <div class="bg-white shadow rounded-lg p-6 mt-4">
      <h2 class="text-xl font-semibold text-gray-800 mb-4">User Invitations</h2>
      
      <!-- Invite Form -->
      <div class="mb-8 bg-gray-50 rounded-lg border border-gray-200 p-6">
        <h3 class="text-lg font-medium text-gray-700 mb-4">Invite New User</h3>
        
        <Form
          :model="inviteForm"
          layout="vertical"
          @finish="handleInviteSubmit"
        >
          <Row :gutter="16">
            <Col :span="12">
              <Form.Item
                label="Email"
                name="email"
                :rules="[
                  { required: true, message: 'Please enter email' },
                  { type: 'email', message: 'Please enter a valid email' }
                ]"
              >
                <Input v-model:value="inviteForm.email" placeholder="Enter email address" />
              </Form.Item>
            </Col>
            
            <Col :span="12">
              <Form.Item
                label="Role"
                name="role"
                :rules="[{ required: true, message: 'Please select a role' }]"
              >
                <Select v-model:value="inviteForm.role" placeholder="Select role">
                  <Select.Option value="USER">User</Select.Option>
                  <Select.Option value="ADMIN">Admin</Select.Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>
          
          <Form.Item
            label="Message (Optional)"
            name="message"
          >
            <Input.TextArea v-model:value="inviteForm.message" rows="3" placeholder="Add a personal message to the invitation email" />
          </Form.Item>
          
          <Form.Item>
            <Button type="primary" html-type="submit" :loading="submitting">
              <template #icon><MailOutlined /></template>
              Send Invitation
            </Button>
          </Form.Item>
        </Form>
      </div>
      
      <!-- Invitations Table -->
      <div>
        <div class="flex justify-between items-center mb-4">
          <h3 class="text-lg font-medium text-gray-700">Pending Invitations</h3>
          <Button type="primary" @click="fetchInvitations">
            <template #icon><ReloadOutlined /></template>
            Refresh
          </Button>
        </div>
        
        <Table
          :columns="columns"
          :data-source="invitations"
          :loading="loading"
          :pagination="{ pageSize: 10 }"
          row-key="id"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'status'">
              <Tag :color="getStatusColor(record.status)">
                {{ record.status }}
              </Tag>
            </template>
            
            <template v-if="column.key === 'actions'">
              <Space>
                <Button 
                  type="primary" 
                  size="small" 
                  :disabled="record.status !== 'PENDING'"
                  @click="resendInvitation(record)"
                >
                  <template #icon><MailOutlined /></template>
                  Resend
                </Button>
                <Button 
                  type="primary" 
                  danger 
                  size="small" 
                  :disabled="record.status !== 'PENDING'"
                  @click="confirmCancelInvitation(record)"
                >
                  <template #icon><DeleteOutlined /></template>
                  Cancel
                </Button>
              </Space>
            </template>
          </template>
        </Table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useAuthStore } from '@/stores/auth'
import api from '@/services/api'
import { useToast } from '@/components/ui/ToastContainer.vue'
import Breadcrumb from '@/components/ui/Breadcrumb.vue'
import { Button, Table, Space, Tag, Modal, Form, Input, Select, Row, Col } from 'ant-design-vue'
import { MailOutlined, DeleteOutlined, ReloadOutlined } from '@ant-design/icons-vue'

// Initialize auth store and toast
const authStore = useAuthStore()
const toast = useToast()

// Breadcrumb items
const breadcrumbItems = [
  { text: 'Dashboard', to: '/admin' },
  { text: 'Users', to: '/admin/users' },
  { text: 'Invitations', to: '/admin/users/invites', active: true }
]

// State
const loading = ref(false)
const submitting = ref(false)
const invitations = ref<any[]>([])

// Invite form
const inviteForm = ref({
  email: '',
  role: 'USER',
  message: ''
})

// Table columns
const columns = [
  {
    title: 'Email',
    dataIndex: 'email',
    key: 'email',
    sorter: (a: any, b: any) => a.email.localeCompare(b.email)
  },
  {
    title: 'Role',
    dataIndex: 'role',
    key: 'role',
    filters: [
      { text: 'User', value: 'USER' },
      { text: 'Admin', value: 'ADMIN' }
    ],
    onFilter: (value: string, record: any) => record.role === value
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
    filters: [
      { text: 'Pending', value: 'PENDING' },
      { text: 'Accepted', value: 'ACCEPTED' },
      { text: 'Expired', value: 'EXPIRED' },
      { text: 'Cancelled', value: 'CANCELLED' }
    ],
    onFilter: (value: string, record: any) => record.status === value
  },
  {
    title: 'Invited By',
    dataIndex: 'invitedBy',
    key: 'invitedBy',
    render: (text: string, record: any) => record.invitedBy?.fullName || 'System'
  },
  {
    title: 'Invited At',
    dataIndex: 'createdAt',
    key: 'createdAt',
    render: (text: string) => new Date(text).toLocaleString(),
    sorter: (a: any, b: any) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
  },
  {
    title: 'Expires At',
    dataIndex: 'expiresAt',
    key: 'expiresAt',
    render: (text: string) => text ? new Date(text).toLocaleString() : 'Never',
    sorter: (a: any, b: any) => {
      if (!a.expiresAt) return 1
      if (!b.expiresAt) return -1
      return new Date(a.expiresAt).getTime() - new Date(b.expiresAt).getTime()
    }
  },
  {
    title: 'Actions',
    key: 'actions'
  }
]

// Fetch invitations
const fetchInvitations = async () => {
  try {
    loading.value = true
    
    const response = await api.get('/admin/invitations', {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    // Process response
    if (response.data && response.data.data) {
      invitations.value = response.data.data
    } else {
      invitations.value = response.data || []
    }
  } catch (error) {
    console.error('Error fetching invitations:', error)
    toast.error('Failed to load invitations')
  } finally {
    loading.value = false
  }
}

// Get status color
const getStatusColor = (status: string) => {
  switch (status) {
    case 'PENDING':
      return 'blue'
    case 'ACCEPTED':
      return 'green'
    case 'EXPIRED':
      return 'orange'
    case 'CANCELLED':
      return 'red'
    default:
      return 'default'
  }
}

// Send invitation
const handleInviteSubmit = async () => {
  try {
    submitting.value = true
    
    const response = await api.post('/admin/invitations', inviteForm.value, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    // Add to list
    const newInvitation = response.data.data || response.data
    invitations.value.unshift(newInvitation)
    
    // Reset form
    inviteForm.value = {
      email: '',
      role: 'USER',
      message: ''
    }
    
    toast.success('Invitation sent successfully')
  } catch (error) {
    console.error('Error sending invitation:', error)
    toast.error('Failed to send invitation')
  } finally {
    submitting.value = false
  }
}

// Resend invitation
const resendInvitation = async (invitation: any) => {
  try {
    loading.value = true
    
    await api.post(`/admin/invitations/${invitation.id}/resend`, {}, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    toast.success('Invitation resent successfully')
    
    // Refresh list
    await fetchInvitations()
  } catch (error) {
    console.error('Error resending invitation:', error)
    toast.error('Failed to resend invitation')
  } finally {
    loading.value = false
  }
}

// Cancel invitation
const confirmCancelInvitation = (invitation: any) => {
  Modal.confirm({
    title: 'Are you sure you want to cancel this invitation?',
    content: 'This action cannot be undone.',
    okText: 'Yes, Cancel Invitation',
    okType: 'danger',
    cancelText: 'No',
    onOk: () => cancelInvitation(invitation.id)
  })
}

const cancelInvitation = async (invitationId: string) => {
  try {
    loading.value = true
    
    await api.delete(`/admin/invitations/${invitationId}`, {
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })
    
    // Update status in list
    const index = invitations.value.findIndex(inv => inv.id === invitationId)
    if (index !== -1) {
      invitations.value[index].status = 'CANCELLED'
    }
    
    toast.success('Invitation cancelled successfully')
  } catch (error) {
    console.error('Error cancelling invitation:', error)
    toast.error('Failed to cancel invitation')
  } finally {
    loading.value = false
  }
}

// Initialize on mount
onMounted(() => {
  fetchInvitations()
})
</script>

// auth-client-react/src/pages/admin/users/UserInvites.tsx
import React, { useState, useEffect } from 'react';
import { 
  Card, 
  Table, 
  Button, 
  Typography, 
  Space, 
  Modal, 
  Form, 
  Input, 
  Select, 
  Popconfirm, 
  message,
  Tag,
  Badge
} from 'antd';
import { 
  PlusOutlined, 
  SendOutlined, 
  DeleteOutlined, 
  ExclamationCircleOutlined,
  MailOutlined
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import adminService from '../../../services/admin.service';

const { Title, Text } = Typography;
const { Option } = Select;

interface InviteData {
  id: string;
  email: string;
  role: string;
  status: 'pending' | 'accepted' | 'expired';
  createdAt: string;
  expiresAt: string;
  createdBy: string;
}

const UserInvites: React.FC = () => {
  const [invites, setInvites] = useState<InviteData[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [modalVisible, setModalVisible] = useState<boolean>(false);
  const [pagination, setPagination] = useState({
    current: 1,
    pageSize: 10,
    total: 0,
  });
  const [form] = Form.useForm();

  // Fetch invites on component mount and pagination change
  useEffect(() => {
    fetchInvites();
  }, [pagination.current, pagination.pageSize]);

  const fetchInvites = async () => {
    try {
      setLoading(true);
      const data = await adminService.getInvites(pagination.current, pagination.pageSize);
      setInvites(data.invites);
      setPagination({
        ...pagination,
        total: data.total,
      });
    } catch (error) {
      console.error('Failed to fetch invites:', error);
      message.error('Failed to load invites');
    } finally {
      setLoading(false);
    }
  };

  const showAddModal = () => {
    form.resetFields();
    setModalVisible(true);
  };

  const handleCancel = () => {
    setModalVisible(false);
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      
      await adminService.createInvite(values);
      message.success('Invitation sent successfully');
      
      setModalVisible(false);
      fetchInvites();
    } catch (error) {
      console.error('Form submission failed:', error);
    }
  };

  const handleResend = async (id: string) => {
    try {
      await adminService.resendInvite(id);
      message.success('Invitation resent successfully');
      fetchInvites();
    } catch (error) {
      console.error('Failed to resend invite:', error);
      message.error('Failed to resend invitation');
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await adminService.deleteInvite(id);
      message.success('Invitation deleted successfully');
      fetchInvites();
    } catch (error) {
      console.error('Failed to delete invite:', error);
      message.error('Failed to delete invitation');
    }
  };

  const handleTableChange = (pagination: any) => {
    setPagination({
      ...pagination,
      current: pagination.current,
      pageSize: pagination.pageSize,
    });
  };

  const getStatusTag = (status: string) => {
    switch (status) {
      case 'pending':
        return <Tag color="blue">Pending</Tag>;
      case 'accepted':
        return <Tag color="green">Accepted</Tag>;
      case 'expired':
        return <Tag color="red">Expired</Tag>;
      default:
        return <Tag>Unknown</Tag>;
    }
  };

  const columns: ColumnsType<InviteData> = [
    {
      title: 'Email',
      dataIndex: 'email',
      key: 'email',
    },
    {
      title: 'Role',
      dataIndex: 'role',
      key: 'role',
      render: (role: string) => (
        <Tag color="purple">{role}</Tag>
      ),
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => getStatusTag(status),
    },
    {
      title: 'Created',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date: string) => new Date(date).toLocaleDateString(),
    },
    {
      title: 'Expires',
      dataIndex: 'expiresAt',
      key: 'expiresAt',
      render: (date: string) => {
        const expiryDate = new Date(date);
        const now = new Date();
        const isExpired = expiryDate < now;
        
        return (
          <span style={{ color: isExpired ? '#f5222d' : 'inherit' }}>
            {expiryDate.toLocaleDateString()}
          </span>
        );
      },
    },
    {
      title: 'Created By',
      dataIndex: 'createdBy',
      key: 'createdBy',
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 150,
      render: (_, record) => (
        <Space size="middle">
          {record.status === 'pending' && (
            <Button
              type="primary"
              icon={<SendOutlined />}
              size="small"
              onClick={() => handleResend(record.id)}
            >
              Resend
            </Button>
          )}
          <Popconfirm
            title="Are you sure you want to delete this invitation?"
            onConfirm={() => handleDelete(record.id)}
            okText="Yes"
            cancelText="No"
            icon={<ExclamationCircleOutlined style={{ color: 'red' }} />}
          >
            <Button
              type="primary"
              danger
              icon={<DeleteOutlined />}
              size="small"
            />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <Title level={2}>User Invitations</Title>
        <Button
          type="primary"
          icon={<PlusOutlined />}
          onClick={showAddModal}
        >
          Invite User
        </Button>
      </div>

      <Card>
        <Text className="block mb-4">
          Manage invitations for new users to join the platform.
        </Text>
        <Table
          columns={columns}
          dataSource={invites}
          rowKey="id"
          loading={loading}
          pagination={pagination}
          onChange={handleTableChange}
        />
      </Card>

      <Modal
        title="Invite New User"
        open={modalVisible}
        onCancel={handleCancel}
        onOk={handleSubmit}
      >
        <Form
          form={form}
          layout="vertical"
        >
          <Form.Item
            name="email"
            label="Email Address"
            rules={[
              { required: true, message: 'Please enter an email address' },
              { type: 'email', message: 'Please enter a valid email address' },
            ]}
          >
            <Input prefix={<MailOutlined />} placeholder="user@example.com" />
          </Form.Item>

          <Form.Item
            name="role"
            label="Role"
            rules={[{ required: true, message: 'Please select a role' }]}
          >
            <Select placeholder="Select a role">
              <Option value="USER">User</Option>
              <Option value="ADMIN">Admin</Option>
              <Option value="CONTENT_EDITOR">Content Editor</Option>
              <Option value="ANALYST">Analyst</Option>
            </Select>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default UserInvites;
